# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harpreet Singh
email: singhh@tcd.ie
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Developer currently a Master's Student at Trinity College Dublin
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

author:
  name: Harpreet Singh
  email: "singhh@tcd.ie"  
  github: etSingh    
  twitter: _etSingh   
  linkedin: etSingh    

include:
  - _pages
# Build settings
markdown: kramdown
sass:
  style: compressed
# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
